#!/usr/bin/env python3
"""Convert lv_font_conv 1.5.3 C output into games/biscuit/generated/fonts.h (os/font.h tables, no LVGL).

    for n in 16 20 24 28; do git show biscuit-v0.1.0:apps/biscuit/firmware/generated/font$n.c > build/font$n.c; done
    python3 games/biscuit/tools/fontconv.py build/font{16,20,24,28}.c

Run from apps/porthole. The inputs are the fonts of Biscuit's LVGL firmware (tag biscuit-v0.1.0). To add a glyph,
first regenerate them from Montserrat-Regular.ttf (same tag, apps/biscuit/assets/fonts/) with the same converter and
flags (that tag's apps/biscuit/firmware/tools/export-fonts.mjs):

    npx lv_font_conv@1.5.3 --font Montserrat-Regular.ttf --range 0x20-0x7e,0xb7,0xe9,0xf6 --size N --bpp 4
        --format lvgl --no-compress --lv-include lvgl.h --lv-font-name biscuit_font_N --output fontN.c

The converter's layout is checked, not assumed: 4 bpp plain bitmaps, class kerning at kern_scale 16, ASCII 32..126
as glyphs 1..95 and a sparse list of extra code points after it. Anything else stops the conversion.
"""

import re
import sys
from pathlib import Path

OUT = Path("games/biscuit/generated/fonts.h")


def array(src: str, name: str) -> list[int]:
    m = re.search(rf"\b{name}\[\]\s*=\s*\{{(.*?)\}};", src, re.S)
    if not m:
        sys.exit(f"fontconv: no {name}[] in the input")
    return [int(v, 0) for v in re.findall(r"-?(?:0x[0-9a-fA-F]+|\d+)", m[1])]


def field(src: str, name: str) -> int:
    m = re.search(rf"\.{name}\s*=\s*(-?\d+)", src)
    if not m:
        sys.exit(f"fontconv: no .{name} in the input")
    return int(m[1])


def expect(ok: bool, what: str) -> None:
    if not ok:
        sys.exit(f"fontconv: unexpected converter output: {what}")


def convert(path: Path) -> tuple[int, str, list[int]]:
    raw = path.read_text(encoding="utf-8")
    src = re.sub(r"/\*.*?\*/", "", raw, flags=re.S)
    m = re.search(r"Size: (\d+) ?px", raw)  # the converter's header comment, or export-fonts.mjs's version of it
    expect(m is not None, "no size in the header comment")
    size = int(m[1]) if m else 0
    for name, want in (("bpp", 4), ("bitmap_format", 0), ("kern_scale", 16), ("kern_classes", 1), ("cmap_num", 2)):
        expect(field(src, name) == want, f"{name} != {want}")
    cmaps = re.findall(r"\.range_start = (\d+), \.range_length = (\d+), \.glyph_id_start = (\d+),.*?\.type = (\w+)", src, re.S)
    expect(len(cmaps) == 2 and cmaps[0] == ("32", "95", "1", "LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY"), "first cmap is not ASCII 32..126 as glyphs 1..95")
    expect(cmaps[1][2] == "96" and cmaps[1][3] == "LV_FONT_FMT_TXT_CMAP_SPARSE_TINY", "second cmap is not a sparse list from glyph 96")
    extras = [int(cmaps[1][0]) + o for o in array(src, "unicode_list_1")]
    glyphs = re.findall(r"\{\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), \.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)\}", src)
    expect(len(glyphs) == 96 + len(extras), f"{len(glyphs)} glyph descriptions for {95 + len(extras)} glyphs")
    left, right, values = array(src, "kern_left_class_mapping"), array(src, "kern_right_class_mapping"), array(src, "kern_class_values")
    lcnt, rcnt = field(src, "left_class_cnt"), field(src, "right_class_cnt")
    expect(len(left) == len(right) == len(glyphs) and len(values) == lcnt * rcnt, "kerning table sizes")
    expect(max(left) <= lcnt and max(right) <= rcnt and all(-128 <= v < 128 for v in values), "kerning classes or values out of range")
    bitmap = array(src, "glyph_bitmap")
    n = f"FONT{size}"

    def rows(vals: list[int], per: int = 24) -> str:
        return ",\n".join("  " + ", ".join(str(v) for v in vals[i : i + per]) for i in range(0, len(vals), per))

    glyph_rows = ",\n".join("  {" + ", ".join(g) + "}" for g in glyphs)
    body = f"""
// Montserrat Regular {size} px: line height {field(src, "line_height")}, baseline {field(src, "base_line")} px from the bottom.
inline constexpr uint8_t {n}_BITMAP[] = {{
{rows([int(v) for v in bitmap], 32)}
}};
inline constexpr font::Glyph {n}_GLYPHS[] = {{
{glyph_rows}
}};
inline constexpr uint8_t {n}_KERN_LEFT[] = {{
{rows(left)}
}};
inline constexpr uint8_t {n}_KERN_RIGHT[] = {{
{rows(right)}
}};
inline constexpr int8_t {n}_KERN[] = {{
{rows(values)}
}};
inline constexpr font::Font {n} = {{{n}_BITMAP, {n}_GLYPHS, EXTRAS, {len(extras)}, {n}_KERN_LEFT, {n}_KERN_RIGHT, {n}_KERN, {rcnt}, \
{field(src, "line_height")}, {field(src, "base_line")}}};
"""
    return size, body, extras


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    fonts = sorted(convert(Path(p)) for p in sys.argv[1:])
    extras = fonts[0][2]
    if any(f[2] != extras for f in fonts):
        sys.exit("fontconv: the fonts cover different code points")
    head = f"""// AUTO-GENERATED by games/biscuit/tools/fontconv.py from lv_font_conv 1.5.3 output. Do not edit.
// Montserrat Regular {"/".join(str(f[0]) for f in fonts)} px, 4 bpp, class kerning: ASCII 32..126 plus \
{" ".join(f"U+{c:04X}" for c in extras)}.
// Copyright 2024 The Montserrat.Git Project Authors (https://github.com/JulietaUla/Montserrat.git).
// SIL Open Font License 1.1: see OFL.txt next to this file.
#pragma once
#include <stdint.h>
#include "font.h"

namespace biscuit {{
inline constexpr uint16_t EXTRAS[] = {{{", ".join(f"0x{c:04X}" for c in extras)}}};
"""
    OUT.write_text(head + "".join(f[1] for f in fonts) + "}  // namespace biscuit\n", encoding="utf-8")
    print(f"wrote {OUT}: {', '.join(f'{f[0]} px' for f in fonts)}")


if __name__ == "__main__":
    main()
