#!/usr/bin/env python3
"""Biscuit's launcher icon: a 32x32 indexed sprite (the launcher is the shell's, so the icon is in the 32-color palette).

Biscuit's golden pup with its dark floppy ears, peeking over an open book. Drawn as flat fills in art.py's ASCII
legend, then given art.py's 1 px inner outline, like the shell's avatars.
Emits games/biscuit/generated/icon.h and a preview at build/art/biscuit_icon.png (needs Pillow for the preview).
Run from anywhere (it chdirs to apps/porthole). `--check` exits 1 if the header is stale.
"""

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "pets-club", "tools"))
from art import K, T, ascii_img  # noqa: E402

HEADER = "games/biscuit/generated/icon.h"
PREVIEW = "build/art/biscuit_icon.png"
ICON = """
................................
................................
..........tttttttttttt..........
........tttttttttttttttt........
.......tttttttttttttttttt.......
...XXXttttttttttttttttttttXXX...
..XXXXXttttttttttttttttttXXXXX..
.XXXXXXttttttttttttttttttXXXXXX.
.XXXXXXttttttttttttttttttXXXXXX.
.XXXXXXttkwkttttttttkwkttXXXXXX.
.XXXXXXttkkkttttttttkkkttXXXXXX.
.XXXXXXttkkkttttttttkkkttXXXXXX.
.XXXXXXttttttttttttttttttXXXXXX.
.XXXXXXtRRtttcccccctttRRtXXXXXX.
..XXXXXttttcccckkcccctttttXXXX..
..XXXXXtttccccckkccccctttXXXXX..
...XXXXtttcccckcckcccctttXXXX...
...XXXXttttccccccccctttttXXXX...
....XXXXtttttccccctttttXXXX.....
.....XXX.ttttttttttttt..XXX.....
................................
..wwwwwwwwwwww..wwwwwwwwwwwww...
.vwwwwwwwwwwwwwvwwwwwwwwwwwwwwv.
.vwllllllllwwwwvwwwwllllllllwwv.
.vwwwwwwwwwwwwwvwwwwwwwwwwwwwwv.
.vwllllllllllwwvwwllllllllllwwv.
.vwwwwwwwwwwwwwvwwwwwwwwwwwwwwv.
.vwllllllllwwwwvwwwwllllllwwwwv.
.vwwwwwwwwwwwwwvwwwwwwwwwwwwwwv.
.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.
..vvvvvvvvvvvvvvvvvvvvvvvvvvvv..
................................
"""


def sprite():
    im = ascii_img(ICON)
    assert im.w == 32 and im.h == 32, "the launcher slot fits a 32x32 icon"
    im.outline(K)
    return im


def emit(check=False):
    im = sprite()
    text = "\n".join(
        [
            "// AUTO-GENERATED by games/biscuit/tools/icon.py. Edit the generator, not this file.",
            "#pragma once",
            '#include "gfx.h"',
            "namespace biscuit {",
            f"static const uint8_t biscuit_icon_px[] = {{{','.join(str(c) for row in im.px for c in row)}}};",
            f"static const gfx::Sprite SPR_BISCUIT_ICON = {{{im.w},{im.h},biscuit_icon_px}};",
            "}  // namespace biscuit",
        ]
    )
    text += "\n"
    if check:
        current = Path(HEADER).read_text(encoding="utf-8") if Path(HEADER).exists() else ""
        if current != text:
            print(f"{HEADER} is out of date: run `python3 games/biscuit/tools/icon.py`")
            sys.exit(1)
        print(f"{HEADER} up to date")
        return
    Path(HEADER).write_text(text, encoding="utf-8")
    print(f"wrote {HEADER}")
    preview(im)


def preview(im):
    try:
        from PIL import Image
    except ImportError:
        print("Pillow missing; skipping preview")
        return
    src = Path("os/palette.h").read_text(encoding="utf-8")
    pal = [int(h, 16) for h in re.findall(r"0x[0-9A-Fa-f]{6}", src[src.index("PALETTE_RGB") :])[:32]]
    z = 12
    img = Image.new("RGB", (im.w * z, im.h * z), (255, 255, 255))
    for y in range(im.h):
        for x in range(im.w):
            c = im.px[y][x]
            if c != T:
                rgb = pal[c]
                img.paste(((rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255), (x * z, y * z, x * z + z, y * z + z))
    os.makedirs(os.path.dirname(PREVIEW), exist_ok=True)
    img.save(PREVIEW)
    print(f"wrote {PREVIEW}")


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/../../..")
    emit(check="--check" in sys.argv)
