// Level 3 stories (ages 8-10). Spliced into BOOKS[] by content.h. Limits: see tools/check_content.py.
  {"Library at Night", C_PLUM, 6, 3, {
    "Scout was a curious little dog who lived at the town library with his owner, Mr. Finn, the librarian.",
    "Every single night, Mr. Finn walked through each quiet room, locked the heavy doors, and switched off the lights.",
    "One evening, Scout smelled something peculiar near the squeaky book cart and stopped to sniff it closely.",
    "He did not hear Mr. Finn calling his name, and soon the whole library grew dark, quiet, and still.",
    "Scout crept out from his hiding spot, and in the dim light the tall shelves looked enormous and strange.",
    "Moonlight poured through the tall windows, painting shimmering silver patterns across the wooden floor below.",
    "A soft, scratchy noise came from behind the very bottom shelf, and Scout tiptoed closer to investigate.",
    "It turned out to be only a tiny, twitchy mouse, busily gathering paper scraps to build a cozy nest.",
    "Feeling much braver now, Scout explored the story time corner and curled up there until he fell fast asleep.",
    "In the morning, Mr. Finn unlocked the doors and laughed in surprise, saying, \"How did you get locked in here all night?\"",
    nullptr}, "Why did Scout stop being scared?", {"Just a small mouse", "Mr. Finn found him", "The sun came up"}, 0},
  {"The Lighthouse", C_NAVY, 4, 3, {
    "Ranger lived in a tall, windswept lighthouse with his owner, a patient keeper named Ana, right beside the churning sea.",
    "Ranger's favorite job of the entire day was standing watch over the wide, restless sea from the very top window.",
    "One evening, dark clouds rolled in with surprising speed, and the wind began to howl fiercely against the old stone walls.",
    "A tremendous storm shook the whole lighthouse, and enormous waves crashed again and again against the rocky shore below.",
    "Suddenly, without any warning, the great lamp at the very top flickered twice and then went completely, worryingly dark.",
    "Without that steady light, a ship out at sea could easily crash on the sharp, hidden rocks somewhere in the dark.",
    "Ranger suddenly remembered the old, dusty backup lantern that was always kept in the storage room down at the bottom.",
    "He barked and barked at the closed door until Ana finally understood and followed him down the narrow, creaky stairs.",
    "Together they lit the ancient lantern with shaking hands and hurried it back up all the winding stairs to the window.",
    "The ship's worried captain spotted the small light just in time and steered his vessel safely around the jagged rocks.",
    "By morning the terrible storm had finally passed, and Ana proudly called Ranger her bravest, soggiest little hero.",
    nullptr}, "Why did Ranger lead Ana to the storage room?", {"He wanted a snack", "To find a lantern", "He smelled fish"}, 1},
  {"Stage Fright", C_ROSE, 2, 3, {
    "Basil had proudly been chosen to play the friendly town dog in the school's big spring play this year.",
    "His owner, a girl named Mia, had earned the biggest part of all: playing the brave and clever queen.",
    "Mia practiced her lines out loud every single night, but on the big day she suddenly felt peculiar and shaky.",
    "Backstage, right before the heavy curtain rose, Mia's mind went completely blank and she forgot every single line.",
    "She hesitated nervously by the heavy curtain, far too nervous to take even one small step onto the stage.",
    "Basil trotted out onto the stage first anyway, wagging his tail happily at the enormous, curious crowd of faces.",
    "The whole audience laughed with delight, and Basil turned around, looked straight at Mia, and barked once.",
    "That one small, friendly bark reminded Mia that her very best friend was standing right there beside her.",
    "Mia finally took a deep breath, walked out onto the stage, and her lines came rushing back one by one.",
    "Afterward, Mia hugged Basil very tightly and said the whole play had been better because he was in it.",
    nullptr}, "Why was Mia able to remember her lines?", {"She read a card", "Someone told her", "Basil's bark"}, 2},
  {"The Night Train", C_GOLD, 7, 3, {
    "Willow the little dog was riding the night train with her owner, a young boy named Sam, to visit family far away.",
    "Sam was traveling all the way to visit his Grandma, and he held his backpack tightly on his lap the whole time.",
    "The train rocked gently back and forth in the darkness, and soon Sam fell into a deep, peaceful sleep.",
    "Willow stayed wide awake the whole time, watching the dark countryside race silently past the rain-streaked window.",
    "At one late-night stop, a tired, hurried traveler accidentally picked up the wrong backpack by simple mistake.",
    "Willow noticed the mix-up at once, because that particular backpack smelled exactly like Sam and no one else.",
    "She barked softly and gently tugged at Sam's sleeve until he finally woke up and saw that his bag was gone.",
    "Willow led Sam quickly down the swaying aisle, following the familiar scent all the way to the very last car.",
    "There sat the traveler, puzzled, just about to open the bag and wondering aloud why it smelled like dog treats.",
    "Sam explained the funny mix-up kindly, and the traveler laughed and happily swapped the two backpacks right back.",
    "They reached Grandma's stop just in time, and Sam proudly called Willow the most determined dog on the whole train.",
    nullptr}, "Why did Willow wake Sam up on the train?", {"His bag was taken", "She wanted a walk", "The train stopped"}, 0},
  {"The Bread Thief", C_PINK, 5, 3, {
    "Ember lived at Rosa's cozy little bakery, where the smell of warm bread filled the air every single morning.",
    "Lately, a few soft rolls had mysteriously kept disappearing from the cooling rack before the shop even opened.",
    "Rosa felt puzzled and a little worried, wondering if some sneaky thief was somehow sneaking inside at night.",
    "A few customers even joked that Ember herself was the mysterious bread thief, which made her feel quite sad.",
    "Determined to solve the strange mystery once and for all, Ember decided to stay awake and watch all night.",
    "Just before dawn broke, she heard a faint fluttering sound coming from somewhere near the old window frame.",
    "A small crack in the old glass let in a whole family of hungry, clever little sparrows looking for breakfast.",
    "Ember watched, astonished, as the tiny birds squeezed through the narrow gap and nibbled at the soft rolls.",
    "In the morning, she proudly led Rosa straight to the cracked window to show her the important clue.",
    "Rosa laughed with great relief and had the little crack fixed carefully that very same sunny afternoon.",
    "From then on, Ember happily earned a fresh roll every morning for solving such a peculiar, tasty mystery.",
    nullptr}, "What was really taking the rolls from the bakery?", {"A hungry cat", "Tiny sparrows", "Ember herself"}, 1},
  {"Museum Mystery", C_LAVENDER, 1, 3, {
    "Marbles worked as the friendly guard dog at the town's big history museum, right in the middle of downtown.",
    "He loved napping peacefully beneath the tall, ancient dinosaur skeleton that stood proudly in the main hall.",
    "One evening, Marbles napped so deeply and quietly that every single guard forgot he was still inside.",
    "The lights clicked off, the heavy doors locked tight, and the whole enormous museum went completely quiet.",
    "In the pitch dark, Marbles suddenly woke to a low, mysterious creaking sound coming from somewhere nearby.",
    "His fur stood straight up as a tall, wobbly shadow swayed slowly and silently across the cold marble floor.",
    "Trembling just a little, he crept closer and bravely discovered it was only a window banging in the wind.",
    "Marbles felt rather silly, then curious, and spent the rest of the quiet night exploring every exhibit hall.",
    "In the morning, the guards were completely astonished to find him waiting proudly and calmly by the door.",
    nullptr}, "What was making the mysterious creaking sound?", {"A ghost", "Another guard dog", "A banging window"}, 2},
  {"Snowed In", C_SKY, 0, 3, {
    "Sunny was a big, fluffy dog who lived with a girl named Priya and her dad high up in the snowy mountains.",
    "It was a peculiar little joke around town that a dog named Sunny loved snow far more than warm sunshine.",
    "One weekend, an enormous, howling blizzard trapped the whole family inside their small wooden cabin.",
    "The wind howled outside without stopping, the power went out, and the cabin grew colder and colder by the hour.",
    "Dad searched everywhere he could think of but simply could not remember where he had stacked the winter firewood.",
    "Sunny put her cold nose to the ground and sniffed determinedly through the deep, drifting snow outside.",
    "She led Priya and her dad straight to a snow-covered pile hidden carefully beside the old wooden shed.",
    "Underneath all that cold snow was exactly what the family needed most: a whole dry stack of split firewood.",
    "Soon a warm fire crackled cheerfully in the fireplace, and the whole cabin slowly felt cozy again.",
    "Priya laughed and said that Sunny had finally, truly earned her sunny name after all that cold snow.",
    nullptr}, "How did Sunny help her family stay warm?", {"Found the firewood", "She lit a match", "She hugged them"}, 0},
  {"Grandma's Attic", C_ORANGE, 6, 3, {
    "On a rainy afternoon, Leo and his dog Bramble climbed the creaky wooden stairs to Grandma's dusty attic.",
    "Boxes of old, curious-looking books were stacked everywhere, smelling faintly of paper and forgotten time.",
    "Bramble sniffed curiously at an ancient wooden trunk pushed into a peculiar, shadowy corner of the room.",
    "Leo tried very hard to pry it open, but the rusty old lid was stuck completely, frustratingly tight.",
    "Bramble suddenly sneezed at the thick dust, then pawed curiously at a loose floorboard beside the trunk.",
    "The old floorboard popped open, revealing a small brass key that had been hidden carefully underneath it.",
    "The little key matched the trunk's old lock perfectly, and the heavy lid finally creaked slowly open.",
    "Inside were dozens of storybooks and one faded old photograph of a very small, floppy-eared puppy.",
    "Grandma explained warmly that the puppy in the old photo was actually her own dog from long, long ago.",
    "She smiled and said that old dog had loved books just as much as Bramble clearly and obviously did.",
    nullptr}, "How did Leo and Bramble open the old trunk?", {"Grandma gave a key", "Found a hidden key", "They broke the lid"}, 1},
  {"The Camp Project", C_GREEN, 2, 3, {
    "Pretzel was the friendly camp dog who happily lived at Camp Pinewood every single summer of the year.",
    "Maya was busy building a volcano for the camp's big science fair, which was happening on Friday morning.",
    "She carefully mixed bright red-dyed vinegar and baking soda into a small cardboard mountain shape.",
    "Pretzel, always curious about everything, bumped the table while sniffing at the peculiar, fizzy smell.",
    "The volcano erupted early, foaming everywhere across the table, hours before the judges had even arrived.",
    "Maya felt her stomach drop with disappointment. Her big project seemed completely ruined before it even started.",
    "Determined not to give up so easily, Maya grabbed more supplies and started rebuilding everything at once.",
    "Pretzel helped out by carefully carrying small paper cups in his mouth, one careful trip at a time.",
    "This time Maya explained every single step out loud and clearly as she rebuilt her little mountain.",
    "When the volcano erupted again, right on cue, the judges clapped and cheered the loudest of the entire day.",
    "Maya did not win the first prize, but she won the special award for the very best explanation of all.",
    nullptr}, "What helped Maya win the award?", {"A bigger volcano", "A funny dog trick", "Explaining it well"}, 2},
  {"The Lost Locket", C_LEAF, 3, 3, {
    "Domino was a stray dog who wandered the busy town alone, always searching for scraps of food to eat.",
    "One chilly morning, he found something shiny and half-buried under an old wooden park bench nearby.",
    "It was a small silver locket, shaped like a heart, with a tiny old photograph tucked inside of it.",
    "Domino carried it very gently in his mouth, quite unsure what to do with such a shiny little treasure.",
    "Along the way, a warm bakery smell nearly made him completely forget the precious locket in his mouth.",
    "He trotted past several shops looking for help, but people reluctantly shooed him away, thinking he was a nuisance.",
    "Cold and a little discouraged, Domino curled up quietly near a tall lamppost to rest for a short while.",
    "Nearby, a girl named Ivy was busy taping up flyers with a picture of that very same silver locket.",
    "It had belonged to her late grandmother, and Ivy was truly determined to find it again no matter what.",
    "Domino caught her familiar scent on one flyer and patiently followed it all the way to her front door.",
    "He gently dropped the locket at her feet, and Ivy's grateful family happily gave him a home of his own.",
    nullptr}, "Why did Domino get a home at the end of the story?", {"He returned it", "He knew a trick", "Ivy needed a pet"}, 0},
