// Level 3 spelling words (6-8 letters). Spliced into WORDS[] by content.h.
  {"LIBRARY", "Where the books live"},
  {"PLANET", "A world in outer space"},
  {"ROCKET", "Flies up into space"},
  {"GARDEN", "Where flowers grow"},
  {"BRIDGE", "Crosses over a river"},
  {"FOREST", "Full of many trees"},
  {"THUNDER", "Boom after lightning"},
  {"MONSTER", "A silly made-up creature"},
  {"PUZZLE", "Pieces that fit together"},
  {"SECRET", "Something kept hidden"},
  {"WHISPER", "Speak very very softly"},
  {"JOURNEY", "A long trip somewhere"},
  {"PICNIC", "Eating a meal outdoors"},
  {"BALLOON", "Floats full of air"},
  {"CAPTAIN", "Leader of a ship or team"},
  {"BLANKET", "Keeps you warm in bed"},
  {"RAINBOW", "Colors after the rain"},
  {"KITCHEN", "Room where you cook"},
  {"BACKPACK", "A bag worn on your back"},
  {"SANDWICH", "Bread with food inside"},
  {"COMPASS", "Points you to north"},
  {"LANTERN", "A light you carry along"},
  {"STATION", "Where trains stop and go"},
  {"SUITCASE", "Packed bag for a trip"},
  {"HALLWAY", "A long path inside"},
  {"POCKET", "Small pouch in your coat"},
  {"TICKET", "Paper that lets you ride"},
  {"WINDOW", "Glass you look through"},
  {"MYSTERY", "Hard to figure out"},
  {"TREASURE", "Hidden gold or jewels"},
