#!/usr/bin/env node
// Regeneration only (lv_font_conv via npm exec needs network); the generated font C files are committed.
// Converter CLI: https://github.com/lvgl/lv_font_conv
// LVGL font API: https://docs.lvgl.io/8.3/overview/font.html
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const output = join(root, 'firmware/generated');
const version = '1.5.3';
const sizes = [16, 20, 24, 28];
const checkOnly = process.argv.includes('--check');
assert(process.argv.slice(2).every((arg) => arg === '--check'), 'Only --check is supported');
const source = 'assets/fonts/Montserrat-Regular.ttf';
const license = 'assets/fonts/OFL.txt';
assert((await readFile(join(root, license), 'utf8')).includes('SIL OPEN FONT LICENSE Version 1.1'));
const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
const prefix = ['exec', '--yes', `--package=lv_font_conv@${version}`, '--', 'lv_font_conv'];

function convert(args) {
  const result = spawnSync(npm, [...prefix, ...args], { cwd: root, encoding: 'utf8', timeout: 120_000 });
  if (result.error) throw result.error;
  assert.equal(result.status, 0, result.stderr || result.stdout || 'lv_font_conv failed');
  return result.stdout.trim();
}

assert.equal(convert(['--version']), version, 'Unexpected converter version');
const staging = await mkdtemp(join(tmpdir(), 'biscuit-fonts-'));
const notice = `Copyright 2024 The Montserrat.Git Project Authors (https://github.com/JulietaUla/Montserrat.git).
Derived from ${source}; SIL Open Font License 1.1, see ${license}.
Generated by firmware/tools/export-fonts.mjs with lv_font_conv@${version}; do not edit.`;

try {
  const files = [];
  for (const size of sizes) {
    const name = `font${size}.c`;
    const destination = join(staging, name);
    convert(['--font', source, '--range', '0x20-0x7e,0xb7,0xe9,0xf6',
      '--size', String(size), '--bpp', '4', '--format', 'lvgl', '--no-compress',
      '--lv-include', 'lvgl.h', '--lv-font-name', `biscuit_font_${size}`, '--output', destination]);
    const generated = await readFile(destination, 'utf8');
    // The converter's comment includes the temporary output path. Replace only
    // that comment so generated files are reproducible across checkouts.
    const body = `${generated.replace(/^\/\*[\s\S]*?\*\/\s*/, '').trimEnd()}\n`;
    assert(body.includes(`const lv_font_t biscuit_font_${size} = {`), `Missing font symbol at size ${size}`);
    assert(body.includes('U+00B7') && body.includes('U+00E9') && body.includes('U+00F6'), `Missing extra glyphs at size ${size}`);
    files.push([name, `/*\n${notice}\nSize: ${size}px; 4bpp, uncompressed; printable ASCII + U+00B7, U+00E9 and U+00F6.\n*/\n${body}`]);
  }
  files.push(['fonts.h', `/*\n${notice}\n*/
#pragma once
#include "lvgl.h"
#ifdef __cplusplus
extern "C" {
#endif
${sizes.map((size) => `LV_FONT_DECLARE(biscuit_font_${size});`).join('\n')}
#ifdef __cplusplus
}
#endif
`]);
  if (!checkOnly) await mkdir(output, { recursive: true });
  for (const [name, contents] of files) {
    if (checkOnly) assert.equal(await readFile(join(output, name), 'utf8'), contents, `${name} is stale; regenerate fonts`);
    else await writeFile(join(output, name), contents);
  }
  console.log(`${checkOnly ? 'Verified' : 'Generated'} Montserrat fonts ${sizes.join('/')}px: 98 glyphs each, ASCII + ·/é/ö; lv_font_conv@${version}.`);
} finally {
  await rm(staging, { recursive: true, force: true });
}
