#!/usr/bin/env python3
"""Pixel-art generator for the Porthole shell (profile avatars + shell icons).

Reuses the ASCII helpers of games/pets-club/tools/art.py. Avatars are drawn as the left half of a 20x20
face, mirrored, then given the same 1-px inner outline as the dog rig. Icons are single-color masks meant
for gfx::blitTint, like Pets Club's CHECK/ARROW.
Emits shell/shell_sprites.h and a preview sheet at build/art/shell_sheet.png (needs Pillow for the preview).
Run from apps/porthole/ (or anywhere: it chdirs there). `--check` exits 1 if the header is stale.
"""

import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "games", "pets-club", "tools"))
from art import K, T, ascii_img  # noqa: E402

HEADER = "shell/shell_sprites.h"
SHEET = "build/art/shell_sheet.png"
AV = 20  # avatar size

# Left half (10 columns) of each 20x20 face; mirrored to the right. Legend is art.py's LEGEND.
# Order is the persisted Profile.avatar index: append only, never reorder.
AVATARS = {
    "dog": """
..........
......tttt
....tttttt
..bttttttt
.bbbtttttt
bbbbbttttt
bbbbbttttt
bbbbtwkttt
bbbbtkkttt
bbbbtttttt
bbbbttcccc
.bbbtccckk
.bbbtcccck
..bbtcckck
...btccckp
....tccccp
....ttcccc
.....ttttt
.......ttt
..........
""",
    "cat": """
..........
.l........
.ll.......
.lpl......
.lppl...ll
.lppplllll
llllllldld
lllllllldl
llllgkglll
llllgkglll
llllllllll
ldddllwwwp
lllllwwkwk
ldddlwwwkw
.lllllwwww
.lllllllll
..llllllll
....llllll
..........
..........
""",
    "bunny": """
....www...
...wwwww..
...wwpww..
...wwpww..
...wwpww..
...wwpww..
...wwpww..
..wwwpwwww
.wwwwwwwww
.wwwwwwwww
wwwwwkkwww
wwwwwkkwww
wwppwwwwwp
wwppwwwkwk
wwwwwwwwkw
.wwwwwwwww
.wwwwwwwww
..wwwwwwww
....wwwwww
..........
""",
    "fox": """
..........
.o........
.oo.......
.oDo......
.oDDo.....
.oDDDo....
.ooooooooo
oooooooooo
oooooooooo
ooooowkooo
oooookkooo
wwoooooooo
wwwwoooooo
.wwwwwwooo
..wwwwwwww
...wwwwwkk
....wwwwwk
......wwww
........ww
..........
""",
    "bear": """
..........
.XXXX.....
XXttXX....
XXttXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXwkXXX
XXXXXkkXXX
XXXXXXXXXX
XXXXXXtttt
XXXXXtttkk
XXXXXttttk
.XXXXttktk
.XXXXXttkt
..XXXXtttt
..XXXXXXXX
...XXXXXXX
.....XXXXX
..........
""",
    "owl": """
..........
.B........
.BB.......
.BBBBBBBBB
.BBBBBBBBB
.BBBwwwBBB
.BBwwwwwBB
.BwwkkwwBB
.BwwkkwwBB
.BBwwwwwoo
.nBBwwwBBo
.nnBBBBBBo
.nnBssssss
.nnBssssBs
.nnBsssssB
.nnBsBsBss
.nnBssBsss
..nBssssss
...BBBBBBB
..........
""",
    "frog": """
..........
..........
..ggggg...
.ggwwwgg..
.gwwwwwg..
.gwwkkwg..
.gwwkkwggg
.ggwwwgggg
gggggggggg
ggggggggkg
gggggggggg
gggggggggg
ggkggggggg
gppkgggggg
.ggpkkkkkk
.ggggMMMMM
..gggMMMMM
....gggggg
..........
..........
""",
    "panda": """
..........
.kkkk.....
kkkkkk....
kkkkkkwwww
kkkkwwwwww
.kwwwwwwww
wwwwwwwwww
wwwwkkkwww
wwwkkwkwww
wwkkkkkwww
wwkkkkwwww
wwwkkwwwww
wwwwwwwwkk
wpwwwwwwwk
wppwwwwkwk
.wwwwwwwkw
.wwwwwwwww
..wwwwwwww
....wwwwww
..........
""",
}

ICONS = {
    "PLUS": """
...kkk...
...kkk...
...kkk...
kkkkkkkkk
kkkkkkkkk
kkkkkkkkk
...kkk...
...kkk...
...kkk...
""",
    "LOCK": """
..kkk..
.k...k.
.k...k.
.k...k.
kkkkkkk
kkkkkkk
kkk.kkk
kkk.kkk
kkkkkkk
""",
    "SOUND_ON": """
....k......
...kk....k.
..kkk.k...k
kkkkk..k..k
kkkkk..k..k
kkkkk..k..k
..kkk.k...k
...kk....k.
....k......
""",
    "SOUND_OFF": """
....k......
...kk......
..kkk.k...k
kkkkk..k.k.
kkkkk...k..
kkkkk..k.k.
..kkk.k...k
...kk......
....k......
""",
}


def face(half):
    rows = half.strip("\n").split("\n")
    assert len(rows) == AV and all(len(r) == AV // 2 for r in rows), "avatar half must be 10x20"
    im = ascii_img("\n".join(r + r[::-1] for r in rows))
    im.outline(K)
    return im


def emit(check=False):
    avatars = {name: face(art) for name, art in AVATARS.items()}
    icons = {name: ascii_img(art) for name, art in ICONS.items()}
    assert icons["SOUND_ON"].w == icons["SOUND_OFF"].w and icons["SOUND_ON"].h == icons["SOUND_OFF"].h
    out = [
        "// AUTO-GENERATED by tools/shell_art.py. Edit the generator, not this file.",
        "#pragma once",
        '#include "gfx.h"',
        f"constexpr int NUM_AVATARS = {len(avatars)};",
        "// Profile.avatar index: " + ", ".join(f"{i} {n}" for i, n in enumerate(avatars)),
    ]
    for name, im in avatars.items():
        out.append(f"static const uint8_t avatar_{name}_px[] = {{{','.join(str(c) for row in im.px for c in row)}}};")
    out.append("static const gfx::Sprite SPR_AVATARS[NUM_AVATARS] = {" + ", ".join(f"{{{AV},{AV},avatar_{n}_px}}" for n in avatars) + "};")
    for name, im in icons.items():
        out.append(f"static const uint8_t spr_{name.lower()}_px[] = {{{','.join(str(c) for row in im.px for c in row)}}};")
        out.append(f"static const gfx::Sprite SPR_{name} = {{{im.w},{im.h},spr_{name.lower()}_px}};")
    text = "\n".join(out) + "\n"
    if check:
        try:
            current = open(HEADER).read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print(f"{HEADER} is out of date: run `python3 tools/shell_art.py`")
            sys.exit(1)
        print(f"{HEADER} up to date")
        return
    with open(HEADER, "w") as f:
        f.write(text)
    print(f"wrote {HEADER} ({len(avatars)} avatars, {len(icons)} icons)")
    preview(list(avatars.values()), list(icons.values()))


def preview(avatars, icons):
    try:
        from PIL import Image
    except ImportError:
        print("Pillow missing; skipping preview")
        return
    src = open("os/palette.h").read()
    pal = [int(h, 16) for h in re.findall(r"0x[0-9A-Fa-f]{6}", src[src.index("PALETTE_RGB") :])[:32]]
    # Row 1: avatars at 8x zoom. Row 2: avatars + icons at 3x (true device size), icons on a button-ish bg.
    Z, D, pad = 8, 3, 4
    W = max(len(avatars) * (AV + pad) * Z, 1)
    H = (AV + pad) * Z + (AV + pad) * D * 2
    img = Image.new("RGB", (W, H), (0x60, 0x80, 0x60))
    px = img.load()

    def put(im, ox, oy, s, ink=None):
        for y in range(im.h):
            for x in range(im.w):
                c = im.px[y][x]
                if c == T:
                    continue
                rgb = pal[c if ink is None else ink]
                for dy in range(s):
                    for dx in range(s):
                        px[ox + x * s + dx, oy + y * s + dy] = ((rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255)

    for i, im in enumerate(avatars):
        put(im, i * (AV + pad) * Z, pad * Z // 2, Z)
    y2 = (AV + pad) * Z
    for i, im in enumerate(avatars):
        put(im, i * (AV + pad) * D, y2, D)
    x = len(avatars) * (AV + pad) * D + 10 * D
    for im in icons:
        put(im, x, y2, D, ink=7)  # white, as tinted on an orange/green button
        put(im, x, y2 + (AV + pad) * D, D)  # raw mask
        x += (im.w + 4) * D
    os.makedirs(os.path.dirname(SHEET), exist_ok=True)
    img.save(SHEET)
    print(f"wrote {SHEET}")


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/..")  # apps/porthole, wherever this runs from
    emit(check="--check" in sys.argv)
