// Biscuit's 96 discoveries in 12 topics. Plain data. Each has two pages, a wonder question and the source it was
// checked against. Run pages and wonder through personalize() before drawing. ids and array order are stable: the order
// is DiscoveryId in generated/discovery_art.h (its picture), and saves keep one bit per discovery by index.
#pragma once
#include <stdint.h>

namespace biscuit {
struct Topic { const char* id; const char* name; };
inline constexpr Topic TOPICS[] = {
  {"space", "Space"},
  {"physics", "Physics"},
  {"earth", "Earth"},
  {"nature", "Nature"},
  {"history", "History"},
  {"humanity", "Humanity"},
  {"art", "Art"},
  {"inventions", "Inventions"},
  {"math", "Mathematics"},
  {"animals", "Animals"},
  {"language", "Languages"},
  {"body", "Human body"},
};
constexpr int TOPIC_COUNT = sizeof TOPICS / sizeof TOPICS[0];

struct Discovery {
  const char* id;
  uint8_t topic;                  // index into TOPICS
  const char* title;
  const char* pages[2];
  const char* wonder;             // an open question to talk about
  const char* sourceName;
  const char* sourceUrl;
};

inline constexpr Discovery DISCOVERIES[] = {
  {"space-01", 0, "What keeps the Sun shining?",
   {"The Sun is not a giant campfire. Deep inside it, hydrogen nuclei combine to make helium. This process, nuclear fusion, releases energy.",
    "Ordinary fire needs fuel and oxygen. Fusion works differently: the Sun's intensely hot, compressed core makes it possible. A star is its own kind of furnace."},
   "How would you explain the difference between a candle and a star without using the word \"hot\"?",
   "NASA - Sun facts", "https://science.nasa.gov/sun/facts/"},
  {"space-02", 0, "Could you stand on the Sun?",
   {"The Sun has no solid ground. It is mostly plasma: matter so hot that many electrons have separated from their atoms. Its visible \"surface\" is a layer of gas.",
    "Different parts of the Sun even rotate at different speeds. A rigid ball could not do that; the Sun's material can move and flow."},
   "Imagine a ball whose middle turns faster than its top. What would happen to a stripe painted on it?",
   "NASA - Sun facts", "https://science.nasa.gov/sun/facts/"},
  {"space-03", 0, "Is sunlight arriving late?",
   {"Sunlight takes about eight minutes to reach Earth. The light arriving now left the Sun several minutes ago. Looking across space also means looking into the past.",
    "Astronomers sometimes describe distances using light travel time. A light-year is a distance, not a duration: how far light travels in one year."},
   "If a message takes four minutes to reach a robot and its reply takes four minutes to return, when could you first hear back?",
   "NASA - Solar system and light time", "https://science.nasa.gov/learn/basics-of-space-flight/chapter1-1/"},
  {"space-04", 0, "Why does the Moon keep the same face?",
   {"The Moon turns once on its axis in about the same time it takes to orbit Earth. That matching rhythm keeps roughly the same side facing us.",
    "It is not standing still. Walk around a chair while always facing it: to keep looking inward, your own body must turn as you go."},
   "Try the chair model. Which direction are you facing halfway around, compared with where you began?",
   "NASA - Moon facts", "https://science.nasa.gov/moon/facts/"},
  {"space-05", 0, "Is the far side of the Moon always dark?",
   {"\"Far side\" means the side facing away from Earth. It does not mean permanent darkness. Both sides receive sunlight as the Moon goes around us.",
    "The phases we see depend on how much of the sunlit half faces Earth. A crescent is still a whole Moon; most of its lit half is simply out of our view."},
   "What is the difference between an object changing shape and our view of it changing?",
   "NASA - Moon facts", "https://science.nasa.gov/moon/facts/"},
  {"space-06", 0, "Can a planet finish a year before one spin?",
   {"Venus takes about 225 Earth days to orbit the Sun, but about 243 Earth days to turn once relative to distant stars. Its year is shorter than that full rotation.",
    "A rotation and a sunrise-to-sunrise day are different measurements. Orbiting changes where the Sun appears, so \"day\" can be a surprisingly slippery word."},
   "Invent two clocks for Venus: one counting full spins and one counting years. Which clock reaches one first?",
   "NASA - Venus facts", "https://science.nasa.gov/venus/venus-facts/"},
  {"space-07", 0, "Why is Venus hotter than closer Mercury?",
   {"Being closest to the Sun is not the whole story. Venus has a thick atmosphere that traps heat in an extreme greenhouse effect, making it the hottest planet.",
    "A planet's temperature depends on what happens to incoming and outgoing energy. Distance matters, but so does the atmosphere surrounding it."},
   "If two rooms get the same sunlight, what differences might make one stay warmer after sunset?",
   "NASA - Venus facts", "https://science.nasa.gov/venus/venus-facts/"},
  {"space-08", 0, "Why does Mars look rusty?",
   {"Iron-bearing minerals on Mars have oxidized: they have reacted chemically with oxygen. That rust-colored material helps give the planet its reddish appearance.",
    "Mars is not red everywhere. Its rocks and soil also include browns and golds; reddish dust helps create the overall color we notice from far away."},
   "How could a handful of colored dust change the way a much larger landscape looks from a distance?",
   "NASA - Mars facts", "https://science.nasa.gov/mars/facts/"},
  {"earth-01", 2, "Are continents separate floating rafts?",
   {"Earth's rigid outer layer is divided into tectonic plates. One plate can carry both a continent and ocean floor; coastlines do not neatly mark plate edges.",
    "Many plate boundaries lie beneath the sea. Patterns of earthquakes and volcanoes help scientists work out where those hidden boundaries are."},
   "If coastlines cannot show every plate edge, what other evidence would you draw onto a map?",
   "USGS - What is a tectonic plate?", "https://pubs.usgs.gov/gip/dynamic/tectonic.html"},
  {"earth-02", 2, "Can a piece of ocean floor disappear?",
   {"At some plate boundaries, one plate sinks beneath another. This process is called subduction. Parts of oceanic plates can gradually return into Earth's interior.",
    "Off the Pacific Northwest, the Juan de Fuca Plate is moving beneath North America. The map beneath our feet changes, even when we cannot feel it happening."},
   "Would a map of the world be a permanent picture or a snapshot? What timescale would matter?",
   "USGS - What is a tectonic plate?", "https://pubs.usgs.gov/gip/dynamic/tectonic.html"},
  {"earth-03", 2, "Can an ocean get wider?",
   {"At spreading boundaries, plates move apart and new oceanic crust forms between them. Seafloor spreading helped the Atlantic grow over millions of years.",
    "This is slow movement on a human timescale, but tiny changes repeated for immense spans of time can rearrange the planet."},
   "Imagine adding one sheet of paper to a stack every day. Why can a small repeated change become important?",
   "USGS - Understanding plate motions", "https://pubs.usgs.gov/gip/dynamic/understanding.html"},
  {"earth-04", 2, "How can a collision build a mountain?",
   {"When continental plates converge, enormous forces compress and thicken the crust. The Himalayas grew as India collided with the rest of Eurasia.",
    "Mountains can therefore record motion, not just height. Their rocks hold evidence about a collision far older than any person watching the mountains today."},
   "What clues might a folded sheet of paper offer about how a flat surface can become a ridge?",
   "USGS - Understanding plate motions", "https://pubs.usgs.gov/gip/dynamic/understanding.html"},
  {"earth-05", 2, "Where does a vanished puddle go?",
   {"Some liquid water escapes into the air as water vapor. This change is evaporation. The puddle can shrink without water draining into a visible hole.",
    "Evaporation needs energy. It is part of the water cycle: water moves between the ground, living things, the atmosphere, and other stores."},
   "Why might two equally sized puddles disappear at different speeds on the same day?",
   "USGS - Evaporation and the water cycle", "https://www.usgs.gov/water-science-school/science/evaporation-and-water-cycle"},
  {"earth-06", 2, "Why can evaporation cool things?",
   {"Changing liquid water into vapor takes energy. When evaporation draws energy from a surface, that surface can become cooler.",
    "This is why evaporation is useful in cooling systems. It moves energy as well as water; the water cycle is not just a story about where droplets travel."},
   "Imagine designing a water container to stay cool. Would you want evaporation to happen or prevent it?",
   "USGS - Evaporation and the water cycle", "https://www.usgs.gov/water-science-school/science/evaporation-and-water-cycle"},
  {"earth-07", 2, "Is groundwater an underground river?",
   {"Usually, groundwater occupies tiny spaces and cracks in soil and rock. Think of water in a sponge rather than a giant open tunnel beneath your feet.",
    "Gravity and pressure move this hidden water. How easily it travels depends on the spaces in the material and how well those spaces connect."},
   "Which would let water move through more easily: connected cracks or sealed pockets? What is your reasoning?",
   "USGS - Groundwater flow", "https://www.usgs.gov/water-science-school/science/groundwater-flow-and-water-cycle"},
  {"earth-08", 2, "Can yesterday's rain take centuries to return?",
   {"Some groundwater travels back to streams quickly. Other water sinks into deep underground stores and may remain there for centuries or even thousands of years.",
    "The water cycle is not a single race around a fixed track. Water has many routes, and the geology along a route changes how long the journey takes."},
   "Draw two possible journeys for a raindrop: one very short and one with a long underground pause.",
   "USGS - Groundwater flow", "https://www.usgs.gov/water-science-school/science/groundwater-flow-and-water-cycle"},
  {"physics-01", 1, "Why is the sky blue rather than empty?",
   {"Air molecules scatter sunlight in different directions. Shorter wavelengths, including blue light, scatter more strongly than longer red wavelengths.",
    "That scattered light reaches your eyes from across the sky. The blue is not a solid ceiling overhead; it comes from light interacting with the atmosphere."},
   "Would an airless world have the same daytime sky? Explain your prediction before checking a photograph of the Moon.",
   "NASA Space Place - Blue sky", "https://spaceplace.nasa.gov/blue-sky/en/"},
  {"physics-02", 1, "Why can a sunset turn the sky red?",
   {"Near sunset, sunlight travels through a longer stretch of atmosphere before reaching you. Much of its blue light has been scattered away from that direct path.",
    "More of the red and orange light continues toward you. The Sun has not suddenly changed its recipe; the route its light takes has changed."},
   "Draw two paths through a curved layer of air: one straight down, one nearly sideways. Which crosses more air?",
   "NASA Space Place - Blue sky", "https://spaceplace.nasa.gov/blue-sky/en/"},
  {"physics-03", 1, "Does a prism invent colors?",
   {"White sunlight contains many colors. A prism separates them so that a mixture which looked plain can reveal a spectrum.",
    "Different colors of visible light have different wavelengths. Blue waves are shorter than red waves; what looks like one beam contains this variety."},
   "{pet} suspects the colors were hiding. What is the difference between making something and revealing it?",
   "NASA Space Place - Blue sky", "https://spaceplace.nasa.gov/blue-sky/en/"},
  {"physics-04", 1, "Why does thunder arrive after lightning?",
   {"The flash and the thunder come from the same lightning event, but light travels much faster than sound. Their messages reach you at different times.",
    "Lightning heats nearby air extremely quickly. The rapid expansion produces a shock wave that becomes the sound of thunder."},
   "In a film, should a very distant lightning flash and its thunder happen together? How could the sound designer suggest distance?",
   "UCAR - Thunder and lightning", "https://scied.ucar.edu/learning-zone/storms/thunder-and-lightning"},
  {"physics-05", 1, "Does every lightning flash hit the ground?",
   {"No. Lightning can travel inside a cloud or between clouds. Many flashes never connect with the ground at all.",
    "A storm separates electric charges. When the electrical difference becomes large enough, a discharge can occur through the air."},
   "Imagine drawing a storm's electrical paths. How would your picture differ from a single zigzag reaching a tree?",
   "UCAR - Thunder and lightning", "https://scied.ucar.edu/learning-zone/storms/thunder-and-lightning"},
  {"physics-06", 1, "Why does solid ice float on liquid water?",
   {"Water molecules arrange themselves into an open structure when ordinary ice forms. The same amount of water then occupies more space.",
    "That makes ice less dense than liquid water. Density compares mass with volume; being solid does not automatically mean being denser."},
   "If a cube of ice melts in a bowl, does the amount of water change, or only how its molecules are arranged?",
   "USGS - Water density", "https://www.usgs.gov/water-science-school/science/water-density"},
  {"physics-07", 1, "Why is most of an iceberg hidden?",
   {"Ordinary ice is only a little less dense than water, so most of an iceberg's volume must be underwater while it floats. Its visible tip is a small part of it.",
    "The exact fraction depends on the ice and surrounding water. A dramatic photograph above the surface leaves out much of the object."},
   "Sketch an iceberg with a small visible tip and a much larger submerged shape. What can a photograph fail to tell you?",
   "USGS - Water density", "https://www.usgs.gov/water-science-school/science/water-density"},
  {"physics-08", 1, "Have floating astronauts escaped gravity?",
   {"Gravity still acts on an orbiting space station. Astronauts appear to float because they and their spacecraft are falling together around Earth.",
    "The station also moves sideways fast enough to keep missing the ground as it falls. An orbit is a kind of continuous free fall, not a gravity-free place."},
   "If an astronaut releases a pencil inside the station, why does it not simply drop to the floor as it would at home?",
   "NASA - What is microgravity?", "https://www.nasa.gov/learning-resources/for-kids-and-students/what-is-microgravity-grades-5-8/"},
  {"nature-01", 3, "Is a mushroom a plant?",
   {"Fungi form their own major group of living things. Unlike green plants, they do not make sugars from sunlight through photosynthesis.",
    "Many fungi release enzymes that break down material around them, then absorb nutrients. Their way of feeding is quite different from a leaf's."},
   "If two living things stay in one place, does that prove they get their food in the same way?",
   "Kew - The wonderful world of fungi", "https://www.kew.org/read-and-watch/the-wonderful-world-of-fungi"},
  {"nature-02", 3, "Is the mushroom the whole fungus?",
   {"A mushroom is often a fungus's reproductive structure. Much of the organism consists of fine threads called hyphae, which form a network known as mycelium.",
    "Those threads may grow through soil or decaying wood. The small part you notice can belong to a much larger hidden network."},
   "What other things do we judge by the small visible part, while overlooking the structure beneath?",
   "Kew - The wonderful world of fungi", "https://www.kew.org/read-and-watch/the-wonderful-world-of-fungi"},
  {"nature-03", 3, "Who clears away fallen forest leaves?",
   {"Many fungi break down dead plant material. This decomposition releases nutrients back into the ecosystem, where other organisms can use them.",
    "Decay is part of how a forest keeps functioning. Without decomposers, dead material would accumulate and many nutrients would remain locked inside it."},
   "Design a forest with no decomposers. What changes would you expect after one autumn? After a hundred?",
   "Kew - The wonderful world of fungi", "https://www.kew.org/read-and-watch/the-wonderful-world-of-fungi"},
  {"nature-04", 3, "Is one daisy really one flower?",
   {"What looks like a single daisy flower is a cluster of many tiny flowers, called florets. The central disc and the outer rays are part of that combined structure.",
    "Gathering many small flowers into one visible head lets a visiting pollinator encounter several of them in a single stop."},
   "Look at a photograph of a daisy close up. Which details disappear when you look from far away?",
   "Kew - Plant adaptations", "https://www.kew.org/read-and-watch/how-plants-have-adapted"},
  {"nature-05", 3, "Can a flower work like a lever?",
   {"Some Salvia flowers have a stamen that acts like a lever. When a suitable bee enters, the mechanism places pollen onto the bee's back.",
    "At another flower, that pollen may be transferred. Flower shapes are not merely decoration; their structures can guide encounters with pollinators."},
   "Sketch a flower as if it were a machine. Which part would move, and what would trigger it?",
   "Kew - Plant adaptations", "https://www.kew.org/read-and-watch/how-plants-have-adapted"},
  {"nature-06", 3, "Why does a Venus flytrap wait for a second touch?",
   {"A Venus flytrap usually closes after its trigger hairs are touched twice within about twenty seconds. One accidental bump is often not enough.",
    "The plant responds to a sequence of signals, not just any touch. Its quick-moving trap is a modified leaf, rather than an animal's mouth."},
   "What advantage might two signals have over one when deciding whether something is really moving inside a trap?",
   "Kew - Venus flytrap", "https://www.kew.org/plants/venus-flytrap"},
  {"nature-07", 3, "Where do Venus flytraps live in the wild?",
   {"Venus flytraps are native to a small area of the eastern United States, in North and South Carolina. A famous plant can have a surprisingly restricted homeland.",
    "They grow in nutrient-poor habitats. Catching small animals supplies nutrients that are scarce in the soil around their roots."},
   "Why could losing a small patch of habitat matter enormously to a species, even if the rest of the planet is huge?",
   "Kew - Venus flytrap", "https://www.kew.org/plants/venus-flytrap"},
  {"nature-08", 3, "Why would anyone keep seeds in a freezer?",
   {"Seed banks preserve collections for the future. Many kinds of seeds last longer when carefully dried and kept cold, slowing processes that damage them.",
    "Not every species tolerates this treatment. Some seeds cannot survive drying or conventional freezing, so conservation needs more than one method."},
   "Why is a backup collection useful if a plant still grows in the wild? What could happen before the backup is needed?",
   "Kew - Seed collection", "https://www.kew.org/science/collections-and-resources/collections/seed-collection"},
  {"history-01", 4, "How can a stick become a pen?",
   {"In ancient Mesopotamia, scribes pressed a cut reed into soft clay. Its tip left wedge-shaped marks: the building blocks of cuneiform writing.",
    "Cuneiform was used for several languages, including Sumerian and Akkadian. A writing system and a language are different things: one can serve more than one voice."},
   "If your writing surface were soft clay, which shapes would be easiest to repeat neatly?",
   "British Museum", "https://www.britishmuseum.org/research/projects/making-cuneiform-tablets"},
  {"history-02", 4, "How can one message unlock another?",
   {"The Rosetta Stone carries a decree in three scripts but two languages. Hieroglyphs and Demotic write Egyptian; the third version is in ancient Greek.",
    "Scholars could read Greek. Comparing the versions helped them decipher Egyptian writing, including signs that represented sounds rather than whole ideas."},
   "Imagine finding the same sentence in a familiar script and a mysterious one. What clues might survive even before you know any letters?",
   "British Museum", "https://www.britishmuseum.org/blog/everything-you-ever-wanted-know-about-rosetta-stone"},
  {"history-03", 4, "Can you tie a number in a knot?",
   {"In the Andes, Inca record keepers used knotted cords called khipus. Some preserve numbers in a decimal system: ones, tens, hundreds and thousands.",
    "Counting every knot is not enough. Its type and position on the cord matter. Moving a knot can change its value, much as moving a digit changes a number."},
   "How might you keep two records apart if both were made from cords instead of labeled sheets?",
   "INALCO", "https://www.inalco.fr/en/quechua-oral-numeration-and-its-writing-quipus"},
  {"history-04", 4, "What questions filled Timbuktu's libraries?",
   {"Timbuktu, in Mali, holds handwritten works on astronomy, mathematics, poetry, music and more. Many manuscripts are centuries old; public and family collections preserve them.",
    "Some were written by local scholars; others arrived through book markets across North Africa and beyond. These pages trace journeys made by ideas as well as books."},
   "Which everyday object in your home might reveal what your family was curious about to someone centuries from now?",
   "UNESCO World Heritage Centre", "https://whc.unesco.org/en/news/979"},
  {"history-05", 4, "Where is the city between the temples?",
   {"Angkor in Cambodia is famous for its temples. Around them, Khmer builders also made reservoirs, canals and embankments: a vast system for managing water.",
    "The waterways are evidence of a carefully organized landscape. To understand the city, archaeologists study the spaces between its spectacular buildings too."},
   "If a future explorer studied your town, what would its pipes, paths and drains reveal that its tallest building would not?",
   "UNESCO World Heritage Centre", "https://whc.unesco.org/en/list/668"},
  {"history-06", 4, "How can an ocean swell act like a compass?",
   {"Polynesian wayfinders compare the directions of stars, the Sun and ocean swells to hold a course. A practiced navigator reads several kinds of evidence together.",
    "They check swell directions against the sky: storms can change the waves. Birds, clouds and drifting material provide further clues as a voyage unfolds."},
   "When two clues disagree, how could a navigator decide which one needs checking?",
   "Polynesian Voyaging Society", "https://worldwidevoyage.hokulea.com/education-at-sea/polynesian-navigation/polynesian-non-instrument-wayfinding/holding-a-course/"},
  {"history-07", 4, "Can a grand building reach down instead of up?",
   {"Rani-ki-Vav, in Gujarat, India, is an elaborate stepwell built about a thousand years ago. Stairs descend through seven levels toward a deep water source.",
    "Its designers combined water storage with richly carved galleries and religious imagery. Going to the well meant entering a remarkable underground building."},
   "How would you design a place where a useful daily task also gave people something beautiful to notice?",
   "UNESCO World Heritage Centre", "https://whc.unesco.org/en/list/922"},
  {"history-08", 4, "What can a broken bowl reveal about a city?",
   {"Great Zimbabwe was a major city built by Shona ancestors. Its skilled builders fitted stone walls together without mortar; some walls carry elaborate patterns.",
    "Finds include Chinese porcelain and coins from Kilwa, on the East African coast. Such objects show that the city belonged to trade networks reaching far beyond it."},
   "An object can pass through many hands. What extra evidence would help you trace its route?",
   "UNESCO World Heritage Centre", "https://whc.unesco.org/en/list/364"},
  {"humanity-01", 5, "Can a sentence travel as a whistle?",
   {"On La Gomera in the Canary Islands, Silbo Gomero turns spoken Spanish into whistles. Changes in pitch and interruptions stand for contrasts in speech sounds.",
    "This is much more than a warning signal: skilled whistlers exchange messages. The practice passes between generations and is also taught in island schools."},
   "What would be hardest to preserve if you had to send a familiar sentence using a completely different kind of sound?",
   "UNESCO Intangible Cultural Heritage", "https://ich.unesco.org/es/RL/el-silbo-gomero-lenguaje-silbado-de-la-isla-de-la-gomera-islas-canarias-00172"},
  {"humanity-02", 5, "Can your eyebrows be part of grammar?",
   {"American Sign Language uses hands, facial movements and its own grammar. It is a complete language, rather than English sentences performed with gestures.",
    "There is no single worldwide sign language. British Sign Language and ASL are distinct, even though spoken English is common in both countries."},
   "What possibilities open up when a language can arrange meaning in the space around a speaker?",
   "NIH - Deafness and communication", "https://www.nidcd.nih.gov/health/american-sign-language"},
  {"humanity-03", 5, "How can the same dots carry different languages?",
   {"Braille is a system for reading by touch. Its basic cell has six possible raised-dot positions, arranged in two columns of three.",
    "Braille is a code, not a language. Different braille codes can represent English, Arabic, Chinese and other languages, so a reader still needs to know the language."},
   "How would a page's layout change if a fingertip, rather than an eye, had to find the next line?",
   "American Foundation for the Blind", "https://afb.org/blindness-and-low-vision/braille/what-braille"},
  {"humanity-04", 5, "Can a bridge stay old while its ropes are new?",
   {"Four Quechua-speaking communities in Peru renew the Q'eswachaka suspension bridge each year. Families braid plant fibers into ropes that become its structure.",
    "The renewal brings technical skills, ceremonies and shared work together. Fresh ropes replace worn ones while knowledge passes from experienced builders to younger people."},
   "If every rope is replaced, what makes it the same bridge: its place, its design, its builders, or something else?",
   "UNESCO", "https://www.unesco.org/en/articles/inca-suspension-bridge-restored-peru-0"},
  {"humanity-05", 5, "Can a library live in a performance?",
   {"Kyrgyz epic tellers carry long stories through voice, rhythm and gesture. Their epics weave historical memories with legend, rather than recording events like a diary.",
    "The art combines learning a rich tradition with individual style and improvisation. A familiar story can sound different when another performer brings it to life."},
   "Which parts of a favorite story would you keep fixed, and which could change each time someone told it?",
   "UNESCO Intangible Cultural Heritage", "https://ich.unesco.org/en/RL/art-of-akyns-kyrgyz-epic-tellers-00065?RL=00065"},
  {"humanity-06", 5, "How can one singer seem to sing two lines?",
   {"In a style of Mongolian Kh\u00f6\u00f6mei, a singer sustains a low drone while a higher, whistle-like melody stands out above it. Both come from the same performer.",
    "A voice contains overtones as well as its main pitch. Skilled changes in mouth, tongue and lip shape emphasize selected overtones, making them easier to hear."},
   "When you hear a layered sound, how does your attention choose which part to follow?",
   "UNESCO Intangible Cultural Heritage", "https://ich.unesco.org/en/RL/mongolian-traditional-art-of-khoomei-00396"},
  {"humanity-07", 5, "Who gets the water when a river is shared?",
   {"In Bali, Indonesia, subak associations coordinate irrigation for rice fields. Canals and weirs guide water, while farmers cooperate over a resource they share.",
    "Water temples are part of this system too. Subak links engineering and farming with community decisions and spiritual relationships among people, nature and the divine."},
   "If your field were last along a canal, what agreements would you want everyone upstream to understand?",
   "UNESCO World Heritage Centre", "https://whc.unesco.org/en/list/1194"},
  {"humanity-08", 5, "Why can a calendar need a whole extra month?",
   {"Twelve cycles of the Moon's phases last about 354 days. A year of seasons lasts about 365 days. Those two useful natural clocks do not fit neatly together.",
    "Lunisolar calendars follow both cycles. Some years gain an extra month, keeping lunar months from drifting steadily through the seasons."},
   "If you invented a calendar, which rhythms of life would you want it to track?",
   "Royal Museums Greenwich", "https://www.rmg.co.uk/sites/default/files/Calendars-from-around-the-world.pdf"},
  {"art-01", 6, "How many makers can hide behind one picture?",
   {"Japanese ukiyo-e woodblock prints were often a team effort. An artist designed the image, a carver cut the blocks, a printer added colors and a publisher organized production.",
    "Different color blocks had to meet in exactly the right places. Small guide marks helped the printer align each layer, building a picture through repeated impressions."},
   "If four people helped make an image, how might each person leave a trace of their decisions?",
   "Victoria and Albert Museum", "https://www.vam.ac.uk/articles/japanese-woodblock-prints-ukiyo-e"},
  {"art-02", 6, "Can looking at a painting become a journey?",
   {"A Chinese handscroll is traditionally viewed a section at a time, from right to left. The viewer unrolls a new part while rolling up the part already seen.",
    "You cannot take in the whole scene at once. Landscapes and stories unfold over time, and your hands help decide the pace of the encounter."},
   "What surprise could you place in a picture that a viewer would discover only after slowly unrolling it?",
   "The Metropolitan Museum of Art", "https://www.metmuseum.org/essays/chinese-handscrolls"},
  {"art-03", 6, "How can a small pattern suggest no ending?",
   {"In many works of Islamic art, circles, squares and other shapes combine into intricate geometric patterns. Repeated units interlace to make a much larger design.",
    "A border stops the actual pattern, but your imagination can continue it. Geometry often appears alongside calligraphy and flowing plant forms."},
   "Sketch a repeating pattern on scrap paper. What happens if you deliberately change just one repeated shape?",
   "The Metropolitan Museum of Art", "https://www.metmuseum.org/essays/geometric-patterns-in-islamic-art"},
  {"art-04", 6, "How can cloth carry a conversation?",
   {"Asante and Ewe weavers in Ghana make kente by weaving narrow strips, then sewing them together. The joins help create a larger rhythm of color and pattern.",
    "Named designs can refer to proverbs, events or everyday things. Understanding a cloth can mean learning its social context as well as noticing its colors."},
   "If you designed a cloth for an important day in your life, what could its pattern remember?",
   "Victoria and Albert Museum", "https://www.vam.ac.uk/articles/cloth-of-a-continent-africa-fashion"},
  {"art-05", 6, "How can bark become a surface for art?",
   {"Samoan siapo is barkcloth. Makers prepare the inner bark of paper mulberry and beat it with a wooden tool, spreading the fibers into a wider, thinner sheet.",
    "Sheets can be joined and decorated to form larger works. The material's transformation begins with skilled preparation, before any pattern appears."},
   "When you look at a finished artwork, what parts of the maker's work might be invisible?",
   "Museum of New Zealand Te Papa Tongarewa", "https://collections.tepapa.govt.nz/object/148134"},
  {"art-06", 6, "Can metal behave like a flowing cloth?",
   {"Artist El Anatsui makes enormous hanging works from discarded metal bottle caps. Pieces are flattened, arranged by color and linked with copper wire.",
    "Many small connections let the surface fold and drape. From a distance it can resemble fabric; close up, familiar objects reveal how it was assembled."},
   "What ordinary material might surprise you if thousands of small pieces were joined together?",
   "The Metropolitan Museum of Art", "https://www.metmuseum.org/exhibitions/listings/2008/african-textiles"},
  {"art-07", 6, "Can a finished painting keep its earlier ideas?",
   {"X-rays can help conservators investigate layers hidden in a painting. Paint materials absorb X-rays differently, so some buried shapes become visible in the image.",
    "The result needs careful interpretation: layers overlap. A hidden outline may reveal a changed pose or reused canvas, offering evidence of an artist's revisions."},
   "If every erased line in one of your drawings became visible, what story would those changes tell?",
   "The National Gallery", "https://www.nationalgallery.org.uk/paintings/glossary/x-rays"},
  {"art-08", 6, "How can a shadow become a character?",
   {"In Indonesian wayang kulit, a puppeteer moves flat leather puppets to cast shadows on a screen. Slender rods control their jointed arms.",
    "Voice, movement, singers and musicians bring the stories to life. The puppeteer draws on a large repertoire while adding wit and a distinctive performance."},
   "How could you make a paper character seem curious using only its outline and movement?",
   "UNESCO Intangible Cultural Heritage", "https://ich.unesco.org/en/RL/wayang-00063"},
  {"inventions-01", 7, "Why make letters that can move?",
   {"Jikji was printed in Korea in 1377 using movable metal type. It is the oldest surviving book known to have been printed this way, not proof that printing began then.",
    "Separate pieces of type can be rearranged for another page. Instead of carving every new page as one block, printers can reuse characters in fresh combinations."},
   "What other tool would become more useful if its parts could be rearranged instead of made again?",
   "UNESCO Memory of the World", "https://www.unesco.org/en/memory-world/baegun-hwasang-chorok-buljo-jikji-simche-yojeol-volii-second-volume-anthology-great-buddhist-priests?hub=915"},
  {"inventions-02", 7, "How can old cloth turn into a new page?",
   {"At a traditional paper mill, ground rags become a watery pulp. A papermaker lifts a thin layer onto a mold; water drains away and leaves a mesh of fibers.",
    "The new sheets are pressed and dried. Further treatment can change how they take ink, so making a useful writing surface involves more than making something flat."},
   "Look closely at the torn edge of scrap paper. What clues can you find about what the sheet is made from?",
   "Getty", "https://www.getty.edu/news/papermaking-workshop-drawing-on-blue-exhibition/"},
  {"inventions-03", 7, "What is a compass needle listening to?",
   {"A compass needle is a small magnet free to turn. Earth's magnetic field makes it line up, giving a direction reference even when familiar landmarks are out of sight.",
    "A nearby magnet can pull the needle away from that direction. The needle follows magnetic forces; it does not know where a traveler wants to go."},
   "What other useful instrument might give a misleading answer when something nearby interferes?",
   "Royal Museums Greenwich", "https://www.rmg.co.uk/sites/default/files/KS2%20Compasses%20and%20Magnetism%20on%20Earth.pdf"},
  {"inventions-04", 7, "Can holes tell a loom what to do?",
   {"A Jacquard loom uses a chain of punched cards to control which lengthwise threads rise. Each step helps determine where the crossing thread goes.",
    "Changing the cards changes the woven pattern. The instructions can be stored and used again: an early example of controlling a machine with recorded information."},
   "What task in an imaginary workshop could be controlled by a sequence of simple instructions?",
   "Computer History Museum", "https://www.computerhistory.org/storageengine/punched-cards-control-jacquard-loom/"},
  {"inventions-05", 7, "How much invention fits in a paper bag?",
   {"Margaret Knight developed a machine that folded and glued paper into bags with flat bottoms. She received a patent for it in 1871.",
    "The challenge was to turn a useful shape into a repeatable process. Her machine coordinated the operations needed to produce the bags efficiently."},
   "Choose an ordinary folded object. Which step would be hardest to teach a machine to repeat?",
   "Lemelson-MIT Program", "https://lemelson.mit.edu/resources/margaret-knight"},
  {"inventions-06", 7, "Why can a pause be an invention?",
   {"Garrett Morgan patented a traffic signal in 1923 with a position that stopped traffic in every direction before the flow changed.",
    "His signal was operated by hand. The all-stop interval gave the junction a clearing pause, showing how changing a sequence can improve an existing idea."},
   "Where else might a brief pause between two actions make a busy system work better?",
   "Smithsonian Lemelson Center", "https://invention.si.edu/invention-stories/diverse-voices-inventor-garrett-morgan"},
  {"inventions-07", 7, "What could an inventor learn from a dog's fur?",
   {"Burrs stuck to George de Mestral's clothes and his dog's fur. Under a microscope, he saw tiny hooks that caught on loops in fibers.",
    "That observation helped inspire hook-and-loop fasteners. Turning the idea into a reliable product took years of experiments with materials and manufacturing."},
   "When an everyday annoyance catches your attention, what might examining it closely reveal?",
   "Lemelson-MIT Program", "https://lemelson.mit.edu/resources/george-de-mestral"},
  {"inventions-08", 7, "How can a damaged code still deliver its message?",
   {"QR codes include extra mathematical information for error correction. A reader can use it to reconstruct some data even when part of the pattern is dirty or damaged.",
    "More protection requires more code space. It has limits too: some damage still makes a code unreadable. Reliability comes from planning for imperfect conditions."},
   "When is it worth making a message longer so it can survive a mistake?",
   "DENSO WAVE", "https://www.qrcode.com/en/about/error_correction.html"},
  {"math-01", 8, "How can two digits count anything?",
   {"Binary uses only 0 and 1. Its place values double as you move left: 1, 2, 4, 8, 16. A 1 includes that value; a 0 leaves it out.",
    "So 1101 means 8 + 4 + 0 + 1: thirteen. The number has not changed, only its outfit. Computers store information using patterns of bits."},
   "Invent two symbols for 0 and 1. What would a page of your binary writing look like?",
   "CS Unplugged - University of Canterbury", "https://www.csunplugged.org/static/slides/en/binary-representation/binary-representation-speaker-notes.pdf"},
  {"math-02", 8, "Why does one extra bit double the possibilities?",
   {"Two bits have four patterns: 00, 01, 10, 11. Add a third bit and every old pattern gets two versions, one starting with 0 and one with 1.",
    "That makes eight patterns. Four bits make sixteen. Each extra yes-or-no choice doubles the possible messages, even before you decide what they mean."},
   "Design a tiny flag using three squares, each dark or light. What messages could its eight patterns carry?",
   "CS Unplugged - University of Canterbury", "https://classic.csunplugged.org/documents/books/english/unplugged-book-v1.pdf"},
  {"math-03", 8, "Can an odd number reveal a hidden mistake?",
   {"Arrange two-sided cards in a grid. Add a border so every row and column has an even number of dark cards. This rule is called even parity.",
    "Flip just one card: its row and column now have odd totals. Their crossing locates the change. Several flips can fool this simple error detector."},
   "Draw a small parity grid. What patterns of changes could leave every row and column even?",
   "CS Unplugged - University of Canterbury", "https://www.csunplugged.org/en/topics/error-detection-and-correction/parity-magic-junior/"},
  {"math-04", 8, "How can a triangle count itself?",
   {"Stack dots in rows of 1, 2, 3 and 4. You get a triangle of ten dots. Turn a second copy around and the pair fits into a 4-by-5 rectangle.",
    "The rectangle has twenty dots, so each triangle has half: ten. The same trick works for any number of rows. Two awkward shapes become one easy count."},
   "Draw two five-row dot triangles in different colours. How could they share one rectangle?",
   "NRICH - University of Cambridge", "https://nrich.maths.org/problems/handshakes?tab=teacher"},
  {"math-05", 8, "Why do odd numbers build squares?",
   {"Start with one dot. Add an L-shaped border of three dots to make a 2-by-2 square. Another border of five makes a 3-by-3 square.",
    "The borders keep growing by two: 3, 5, 7, 9. That is why 1 + 3 + 5 + 7 makes sixteen, a 4-by-4 square. A picture can be a mathematical argument."},
   "Sketch a square growing one border at a time. Where does each new border gain its two extra dots?",
   "NRICH - University of Cambridge", "https://nrich.maths.org/problems/picturing-square-numbers"},
  {"math-06", 8, "Why does counting handshakes need a half?",
   {"Six people each shake five other hands. Six times five gives thirty, but every handshake appears twice: once for each person involved.",
    "Halving thirty gives fifteen actual handshakes. Counting from two viewpoints is useful, provided you remember when both views describe the same thing."},
   "Draw six people as dots and handshakes as lines. What else could the same picture represent?",
   "NRICH - University of Cambridge", "https://nrich.maths.org/problems/handshakes?tab=teacher"},
  {"math-07", 8, "Can a loop have only one side?",
   {"Give a paper strip half a twist, then join its ends. You have made a M\u00f6bius strip. The twist connects what seemed to be two different sides.",
    "Trace a line along the middle without lifting your pencil. It travels over both original faces before returning. The finished loop has one continuous side."},
   "Make a paper loop with tape and a half twist. How does tracing its edge compare with tracing its middle?",
   "NRICH - University of Cambridge", "https://nrich.maths.org/making-maths-make-magic-circle"},
  {"math-08", 8, "Why is the middle number so useful?",
   {"Take three neighbours on the number line: 7, 8, 9. Move one from the largest to the smallest, and you get 8, 8, 8. The total stays twenty-four.",
    "So three consecutive whole numbers always add to three times the middle one. Five neighbours balance around their middle too. Symmetry does the work."},
   "Draw five consecutive numbers as towers of squares. How could you rearrange them into equal towers?",
   "NRICH - University of Cambridge", "https://nrich.maths.org/problems/three-neighbours"},
  {"animals-01", 9, "What is hidden inside a dog's nose?",
   {"A dog's nose contains a maze of narrow passages. The folds fit a large scent-detecting surface into a small space. A sniff sends odour molecules inside.",
    "Molecules meet receptors that send signals to the brain. Researchers model these air currents to understand sniffing and help design artificial noses."},
   "If {pet} wrote a map using smells instead of colours, which places might deserve the biggest labels?",
   "Penn State University", "https://www.psu.edu/news/research/story/scent-penn-state-engineers-search-better-artificial-nose"},
  {"animals-02", 9, "Can a dance give directions?",
   {"A honeybee that finds flowers can perform a waggle dance in the hive. Its movements carry information about the direction and distance of the food.",
    "Other bees can use that information on their own journeys. Researchers film and decode dances to discover where colonies are gathering food."},
   "Invent movements that could describe a route to a bookshelf. What information would your dance need?",
   "University of Sussex - LASI", "https://www.sussex.ac.uk/lasi/sussexplan/dances"},
  {"animals-03", 9, "How does an octopus change its skin's colour?",
   {"An octopus has tiny pigment sacs in its skin, called chromatophores. Muscles stretch the sacs wider or let them shrink, changing how much colour shows.",
    "Nerves control the muscles, making patterns change rapidly. An octopus can also raise bumps on its skin. Its disguise can have texture as well as colour."},
   "Design two octopus disguises on paper: one for pebbles and one for seaweed. What must change besides colour?",
   "Smithsonian Ocean", "https://ocean.si.edu/ocean-life/invertebrates/how-octopuses-and-squids-change-color"},
  {"animals-04", 9, "How does a penguin wear air?",
   {"Penguin feathers trap a layer of air next to the body. That trapped air helps insulate the bird from cold water. Its coat contains an invisible ingredient.",
    "Penguins spread oil from a gland near the tail over their feathers while preening. This helps the feather coat repel water and keep doing its job."},
   "Design a fictional underwater coat for {pet}. How would you keep its insulating layer from escaping?",
   "Smithsonian Ocean", "https://ocean.si.edu/ocean-life/seabirds/penguins"},
  {"animals-05", 9, "How can an elephant call hide from human ears?",
   {"Elephants communicate with deep rumbles. Parts of a rumble can be below the range humans can hear. Low pitch does not necessarily mean low volume.",
    "Low-frequency sounds travel well through forests, helping separated elephants stay in contact. A quiet landscape to human ears may contain elephant messages."},
   "Imagine a sound map that includes sounds people cannot hear. Which familiar places might seem less quiet?",
   "Cornell University - Elephant Listening Project", "https://www.birds.cornell.edu/ccb/elephant-listening-project/sound/"},
  {"animals-06", 9, "How does a platypus hunt with its eyes shut?",
   {"A diving platypus closes its eyes, ears and nostrils while searching for food. Its bill contains sensors for pressure and electrical signals.",
    "The bill helps it find small prey on the river bottom. Scientists are still studying exactly how these signals work together. A strange bill, a serious tool."},
   "Invent an explorer's tool for muddy water. What could it measure when a camera would be little help?",
   "Australian Museum", "https://australian.museum/learn/animals/mammals/platypus/"},
  {"animals-07", 9, "How can an echo reveal an insect?",
   {"Many bats send out high-pitched calls and listen for the echoes. Sound bounces from nearby objects, including the insects a bat is hunting.",
    "Returning echoes help the bat locate its surroundings as it flies. This is echolocation: gathering information with sound. Bats can also see."},
   "Imagine drawing a room from its echoes. Which details would be easier to discover than others?",
   "U.S. National Park Service", "https://www.nps.gov/sagu/learn/nature/bats.htm"},
  {"animals-08", 9, "Is a bat's wing a very unusual hand?",
   {"A bat's wing has greatly lengthened finger bones with thin skin stretched between them. Many movable joints let the wing bend and change shape.",
    "That flexible structure helps bats turn and manoeuvre in flight. A bat and a person share a familiar basic hand plan, put to remarkably different uses."},
   "Sketch a bat wing beside your hand. Which parts seem familiar, and which proportions would need changing?",
   "U.S. National Park Service", "https://home.nps.gov/subjects/bats/how-bats-fly.htm"},
  {"language-01", 10, "Can a language have grammar you can see?",
   {"American Sign Language, or ASL, is a complete natural language. Hands, face and body carry meaning. Its grammar differs from English grammar.",
    "It has its own rules for forming words and arranging them. A signed conversation can tell stories, argue ideas or make jokes."},
   "What might a visual language let a storyteller show directly in the space around them?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/american-sign-language"},
  {"language-02", 10, "Is there one sign language for the whole world?",
   {"There are many sign languages. American Sign Language and British Sign Language are distinct, even though English is spoken in both countries.",
    "Knowing one does not automatically mean understanding the other. Signed languages also have regional differences in signs and rhythm."},
   "What could make a travelling signed storyteller's performance easy to follow across language differences?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/american-sign-language"},
  {"language-03", 10, "Can eyebrows be part of a sentence?",
   {"In ASL, facial expressions do grammatical work. Eyebrows, eyes and body position can help signal a question, alongside the hands.",
    "The face is carrying language, not merely showing a mood. Watching only a signer's hands would leave out useful information."},
   "How could a comic show the difference between a character wondering something and stating it?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/american-sign-language"},
  {"language-04", 10, "How can six dots hold a book?",
   {"Braille uses patterns of raised dots that readers feel with their fingertips. A basic cell has six positions: two columns, each three dots high.",
    "Different patterns can represent letters, numbers and punctuation. Cells are small enough to feel with a fingertip, turning a page into a tactile text."},
   "Invent a raised-dot label for a fictional object. What would make nearby symbols easy to tell apart?",
   "Library of Congress - NLS", "https://www.loc.gov/nls/services-and-resources/informational-publications/about-braille/"},
  {"language-05", 10, "How can a whole word fit in one small pattern?",
   {"Braille does not always spell every word letter by letter. Contracted braille uses certain patterns for groups of letters or whole words.",
    "These contractions save space, helping keep raised-dot books less bulky. Readers learn the shared rules so a short pattern carries a longer meaning."},
   "Invent three shortcuts for a message to {pet}. How would you explain the rules so somebody else could read it?",
   "Library of Congress - NLS", "https://www.loc.gov/nls/services-and-resources/informational-publications/about-braille/"},
  {"language-06", 10, "How did three scripts unlock an ancient message?",
   {"The Rosetta Stone repeats a decree in three scripts: Egyptian hieroglyphs, Egyptian Demotic and Greek. Three scripts, but two languages.",
    "Scholars could read the Greek. Comparing its message with the Egyptian writing helped them work out hieroglyphs. Repetition became a clue."},
   "Invent a sign in two scripts, one known and one made up. What clues could help someone decipher your new script?",
   "British Museum", "https://www.britishmuseum.org/blog/everything-you-ever-wanted-know-about-rosetta-stone"},
  {"language-07", 10, "Can a whistle carry a conversation?",
   {"On La Gomera in the Canary Islands, Silbo Gomero turns spoken Spanish into whistles. Changes in pitch and interruptions represent language sounds.",
    "Listeners learn to recover words from those whistle patterns. It is a way to carry messages, rather than a separate wordless tune."},
   "Imagine a message travelling across a valley. What might a whistled version preserve, and what might be harder to distinguish?",
   "UNESCO - Intangible Cultural Heritage", "https://ich.unesco.org/en/RL/whistled-language-of-the-island-of-la-gomera-canary-islands-the-silbo-gomero-00172"},
  {"language-08", 10, "Why might one conversation use two languages?",
   {"Multilingual speakers sometimes switch languages during a conversation, or even within a sentence. Linguists call this code-switching.",
    "A speaker may choose a phrase that fits especially well in another language. Switching can keep the conversation flowing when a word in one language is elusive."},
   "Imagine two characters who share several languages. What might make one character change languages during their story?",
   "Cambridge University Press & Assessment", "https://www.cambridgeenglish.org/news/view/how-english-teachers-can-crack-the-code/"},
  {"body-01", 11, "How does a sound become something you hear?",
   {"Sound waves make your eardrum vibrate. Three tiny bones pass those vibrations into the fluid-filled cochlea inside your inner ear.",
    "The moving fluid bends tiny projections on sensory cells. That helps create electrical signals which travel to the brain. A vibration becomes information."},
   "Imagine designing a machine that notices a whisper. Which part would catch movement, and which would interpret it?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/how-do-we-hear"},
  {"body-02", 11, "Why does your inner ear contain tiny loops?",
   {"Three fluid-filled loops in each inner ear help detect head rotation. They point in different directions, so they can report different kinds of turns.",
    "Moving fluid bends sensory structures. The brain combines these signals with information from eyes and body to help keep track of balance."},
   "Sketch an imaginary explorer robot. Where would you put sensors so it could tell which way it was turning?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/balance-disorders"},
  {"body-03", 11, "Does an eye send pictures to the brain?",
   {"The cornea and lens focus light onto the retina at the back of the eye. There, special cells called photoreceptors respond to light.",
    "They help turn light into electrical signals. The optic nerve carries signals to the brain, which turns that information into the images you see."},
   "Draw the journey from a book's page to a reader's brain. Where does the information change form?",
   "NIH - National Eye Institute", "https://www.nei.nih.gov/learn-about-eye-health/healthy-vision/how-eyes-work"},
  {"body-04", 11, "How can a nose recognise so many smells?",
   {"Odour molecules reach sensory cells high inside the nose. Different molecules can activate different combinations of receptors, which send signals to the brain.",
    "There need not be a separate receptor type for every smell. Combinations create many patterns, rather like a few musical notes making many tunes."},
   "Invent a smell alphabet using a few imaginary signals. How could combinations describe a forest or an old book?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/smell-disorders"},
  {"body-05", 11, "Why does your nose help with flavour?",
   {"Food aromas can reach the nose from behind: through a passage linking the throat and nose. Smell and taste work together to produce much of flavour.",
    "When a blocked nose keeps those aromas from reaching smell cells, familiar foods may seem bland. The tongue is only part of the flavour detective team."},
   "Describe a favourite flavour without naming the food. Which words describe smell, and which describe texture?",
   "NIH - NIDCD", "https://www.nidcd.nih.gov/health/smell-disorders"},
  {"body-06", 11, "How does making more space pull air inside?",
   {"A sheet of muscle called the diaphragm sits below your lungs. When it contracts, it moves downward and makes more room in your chest.",
    "Your lungs expand and air flows in. As the diaphragm relaxes, the lungs recoil and air flows out. Breathing changes space as well as moving air."},
   "Draw two diagrams of the chest, one with the diaphragm higher and one lower. How would you show the changing space?",
   "NIH - NHLBI", "https://www.nhlbi.nih.gov/health/lungs/breathing-benefits"},
  {"body-07", 11, "Where does breathed-in oxygen meet the blood?",
   {"Inside the lungs are tiny air sacs called alveoli, surrounded by small blood vessels. Oxygen crosses their thin walls into the blood.",
    "Red blood cells carry oxygen onward. Carbon dioxide travels the other way, from blood into the air sacs, ready to leave when you breathe out."},
   "Imagine designing an exchange station for two kinds of cargo. How would you give both plenty of room to cross?",
   "NIH - NHLBI", "https://www.nhlbi.nih.gov/health/lungs/breathing-benefits"},
  {"body-08", 11, "Is a skeleton ever really finished?",
   {"Bone is living tissue, constantly being remodelled. Some cells break down old bone while others build new bone. Your skeleton has a maintenance crew.",
    "The builders are called osteoblasts; the cells removing bone are osteoclasts. Both jobs matter as bones renew themselves and grow."},
   "Invent a building that can replace its own worn parts while people still use it. How would its crews coordinate?",
   "NIH - NIAMS", "https://www.niams.nih.gov/health-topics/educational-resources/health-lesson-learning-about-bones"},
};
}  // namespace biscuit
