[platformio]
src_dir = .
extra_configs = ../../../platform/waveshare-round.ini

[env:firmware]
extends = waveshare_round
board_upload.maximum_size = 12582912
board_build.partitions = partitions.csv
extra_scripts =
  pre:tools/gen_assets.py
  post:../../../platform/factory_image.py
build_src_filter = +<src/> +<generated/assets.cpp> +<generated/font*.c>
build_unflags = -std=gnu++11 -std=gnu++14
build_flags =
  ${waveshare_round.build_flags}
  -std=gnu++17
  -DLV_CONF_INCLUDE_SIMPLE
  -Iinclude
  -Igenerated
lib_deps = lvgl/lvgl@8.3.10
upload_speed = 115200
